# programmed by 117CS0233(Bhupati)

In [36]:
import numpy as np, os
import cv2

def LoadData(Dir, Img_Shape):
    Images= []
    Classes=[]
    for(_, Dirs, _) in os.walk(Dir):
        Dirs = sorted(Dirs)
        for SubDir in Dirs:
            SubjectPath = os.path.join(Dir, SubDir)
            for FileName in os.listdir(SubjectPath):
                path = SubjectPath + "/" + FileName
                Img = cv2.imread(path,cv2.IMREAD_GRAYSCALE)

                #print Img.shape
                (height, width) = Img.shape

                if(width != Img_Shape[0] or height != Img_Shape[1]):
                    Img = Img.resize((Img_Shape[0], Img_Shape[1]))
                Img=Img.reshape(Img_Shape[0] * Img_Shape[1])
                #print(type(Img))
                Images.append(Img)
                Classes.append(SubDir)
    return np.array(Images),np.array(Classes)

In [37]:
training_dir = 'ATnT/Training'
imageSize = 92*112
imageWidth = 92
imageHeight = 112

X,Class_X= LoadData(training_dir, (imageWidth, imageHeight))


In [38]:
X.shape,Class_X.shape

((240, 10304), (240,))

In [39]:
mean=[]
for i in X:
    mean.append(i.mean())
X_mean=np.array(mean)
X_mean

array([128.33821817, 147.98893634, 132.59549689, 142.14926242,
       142.77348602, 143.22272904,  95.10277562,  97.07230202,
        99.85685171, 102.80706522, 110.32065217, 108.88848991,
       100.02309783, 101.18410326, 103.75300854, 107.21127717,
       106.94633152,  99.12820264, 129.7804736 , 115.89800078,
       116.24737966, 114.25669643, 115.69574922, 126.85636646,
       125.21477096, 125.41527562, 131.76513975, 128.18565606,
       128.97952252, 131.90799689, 106.48913043, 105.96224767,
       106.90285326, 106.03018245, 104.97932842, 102.19604037,
       111.39343944, 114.84501165, 110.01746894, 109.81677019,
       113.44613742, 112.11898292, 102.67274845, 119.2330163 ,
       122.5617236 , 134.37567935, 132.34704969, 111.39576863,
       116.37354425, 116.15984084, 110.55366848, 109.18623835,
       115.30861801, 110.31570264, 137.13334627, 134.24572981,
       134.68216227, 132.66935171, 134.41653727, 136.48466615,
       119.21593556, 120.92565994, 124.48728649, 125.40

In [40]:
X_zero=[]
for i in range(len(X)):
    X_zero.append(X[i]-X_mean[i])
X_zero=np.array(X_zero)
X_zero

array([[ -80.33821817,  -79.33821817,  -83.33821817, ...,  -81.33821817,
         -82.33821817,  -82.33821817],
       [ -87.98893634,  -87.98893634,  -85.98893634, ..., -115.98893634,
        -113.98893634, -113.98893634],
       [ -93.59549689,  -88.59549689,  -79.59549689, ..., -103.59549689,
        -106.59549689, -103.59549689],
       ...,
       [  -0.15130047,   -4.15130047,   -2.15130047, ...,  -21.15130047,
         -25.15130047,  -28.15130047],
       [  -3.77950311,   -4.77950311,   -2.77950311, ...,  -19.77950311,
         -25.77950311,  -23.77950311],
       [  -1.60461957,   -2.60461957,   -3.60461957, ...,  -27.60461957,
         -27.60461957,  -25.60461957]])

In [41]:
X_zero.shape

(240, 10304)

In [42]:
cov=np.cov(X_zero)
cov.shape

(240, 240)

In [43]:
#Calculate Eigen-Values and Eigen-Vectors
w,v = np.linalg.eig(cov)
#Eigen Vectors
v.shape

(240, 240)

In [44]:
#Eigen Values
w.shape

(240,)

In [45]:
#Descending Sorting
eigen_values= np.ndarray.copy(w)
id(eigen_values)
indexes=[i for i in range(400)]
for i in range(len(w)-1):
    max_idx = i; 
    for j in range(i+1,len(w)):
        if(w[j]>w[max_idx]):
            max_idx = j;
    
    indexes[i],indexes[max_idx]=indexes[max_idx],indexes[i]
    w[i],w[max_idx]=w[max_idx],w[i]
    
w

array([2.32571962e+05, 5.89757035e+04, 2.52853495e+04, 2.25835399e+04,
       1.41978897e+04, 1.19344121e+04, 9.99440964e+03, 8.91544180e+03,
       7.14760115e+03, 6.53772046e+03, 5.38850131e+03, 4.82904247e+03,
       4.56511003e+03, 3.94969822e+03, 3.86906029e+03, 3.72334681e+03,
       3.64843108e+03, 3.21056590e+03, 3.04837039e+03, 2.81878850e+03,
       2.71282171e+03, 2.40380343e+03, 2.32637045e+03, 2.20640673e+03,
       2.09013899e+03, 2.02790275e+03, 1.98761012e+03, 1.90952615e+03,
       1.87629413e+03, 1.75978392e+03, 1.71437621e+03, 1.65957570e+03,
       1.61933704e+03, 1.57215292e+03, 1.50395685e+03, 1.45046760e+03,
       1.42580844e+03, 1.34036253e+03, 1.31579580e+03, 1.28051276e+03,
       1.22175696e+03, 1.19386432e+03, 1.17033583e+03, 1.14621261e+03,
       1.09619917e+03, 1.06780398e+03, 1.00363935e+03, 9.73639809e+02,
       9.66510333e+02, 9.52727663e+02, 9.20333273e+02, 9.16203231e+02,
       8.98768620e+02, 8.82741875e+02, 8.39913104e+02, 8.34981168e+02,
      

In [46]:
w[-5:].astype(int)

array([68, 64, 59, 53, 49])

In [47]:
min(eigen_values),w[-1]

(49.952529153959745, 49.952529153959745)

In [48]:
#Generating feature vector
feature_vector = v[indexes[:50]]
feature_vector

array([[ 0.08967691, -0.00466909, -0.08087694, ...,  0.09336103,
        -0.00564726,  0.00227062],
       [ 0.0416749 , -0.04594069, -0.04629766, ..., -0.04433719,
         0.02631081, -0.12830694],
       [ 0.07595027, -0.05644696, -0.03151799, ..., -0.07036023,
        -0.06222008,  0.01958367],
       ...,
       [ 0.06185228, -0.04803037, -0.12835675, ..., -0.022176  ,
         0.09021569,  0.01357257],
       [ 0.07980831, -0.02170738, -0.04624751, ...,  0.00097053,
         0.02155595,  0.09241259],
       [ 0.07748487,  0.01639579, -0.04914813, ...,  0.00167653,
         0.02739957, -0.03139435]])

In [49]:
feature_vector.shape

(50, 240)

In [50]:
eigen_faces=np.matmul(feature_vector , X_zero)
eigen_faces

array([[ 55.46895242,  55.94741661,  53.2905102 , ..., 104.57031344,
        121.90944003, 115.86180339],
       [ 68.11534893,  61.90200059,  63.10294561, ...,  57.81749853,
         89.35333649,  95.7986285 ],
       [ 24.25572973,  16.72366307,  21.34650129, ...,  -6.755769  ,
          7.6139825 ,  10.90902166],
       ...,
       [ 68.18802249,  69.78376956,  64.38821909, ...,  -8.03955416,
         -6.64559217,   3.585811  ],
       [ -4.0284057 ,  -2.61584307,  -5.24668596, ...,  65.21846486,
         63.80717038,  47.58405376],
       [ 11.73029948,   9.18798102,   4.67479331, ...,  49.48264687,
         36.51914061,  20.61760557]])

In [51]:
eigen_faces.shape

(50, 10304)

In [52]:
signature=[]
trans=np.matrix.transpose(X_zero)
for i in range(len(trans[0])):
    signature.append(np.matmul(eigen_faces , trans[:,i]))
signature = np.array(signature)

In [53]:
signature.shape

(240, 50)

In [54]:
trans[:,i].shape

(10304,)

In [55]:
np.matrix.transpose(X_zero).shape

(10304, 240)

# TESTING

In [56]:
import os
import numpy as np
testing_dir = 'ATnT/Testing'

imageSize = 92*112
imageWidth = 92
imageHeight = 112

X,Class_Y= LoadData(testing_dir, (imageWidth, imageHeight))


In [57]:
X_zero=[]
for i in range(len(X)):
    X_zero.append(X[i]-X_mean[i])
X_zero=np.array(X_zero)
X_zero

array([[ -94.33821817,  -94.33821817,  -95.33821817, ...,  -91.33821817,
         -88.33821817,  -95.33821817],
       [-106.98893634, -100.98893634, -100.98893634, ..., -112.98893634,
        -110.98893634, -109.98893634],
       [ -88.59549689,  -89.59549689, -100.59549689, ...,  -89.59549689,
         -89.59549689,  -95.59549689],
       ...,
       [  23.3289014 ,   20.3289014 ,   27.3289014 , ...,    4.3289014 ,
          -0.6710986 ,    3.3289014 ],
       [  22.05221273,   25.05221273,   23.05221273, ...,   -0.94778727,
          -2.94778727,    3.05221273],
       [  21.06667314,   23.06667314,   24.06667314, ...,    3.06667314,
          -1.93332686,    1.06667314]])

In [58]:
X_zero.shape, eigen_faces.shape

((160, 10304), (50, 10304))

In [59]:
np.matmul(eigen_faces , X_zero[5]).shape

(50,)

In [60]:
proj_test_face=[]
for i in range(len(X_zero)):
    proj_test_face.append(np.matmul(eigen_faces , X_zero[i]))
proj_test_face

[array([-20528015.53378508, -21929048.69619709,  -2330236.22337348,
         10409435.52849464,  11862410.18338547,   4468772.25161484,
         20526339.56235805, -33196585.07969494,    -84209.99044421,
          4776336.46426043,   -331842.54270333,  -2387989.32921718,
          1266723.15634439,    378146.43156038, -22196535.84906356,
          5292438.84498693, -21416107.97388953,   2357094.52504832,
          7565034.26014453,   3668891.75285469, -11266041.64513972,
         19060865.92033676,  29195356.83907235,  -5470254.09886782,
         -6532936.90482819,  -4651628.24081833,   1231204.745009  ,
          3605827.65758456,  23785596.97760347,   -469564.4296711 ,
        -13749649.55546219, -14049281.49828564,  24684031.17533286,
         -6158812.42802073,  -4007949.46737979, -24070021.74949042,
           287911.2742804 ,   2383352.50183309,   3669912.97561075,
         13173657.73384196,   2460561.71356283,  -2013980.63237196,
         -2025534.16518008,  16469333.71085397, 

In [61]:
proj_test_face=np.array(proj_test_face)

In [62]:
def min_index(arr):
    index=0
    for i in range(1,len(arr)):
        if(arr[index] > arr[i]):
            index=i
    return index

In [63]:
dist=[]
index_min=[]
for i in range(len(proj_test_face)):
    d=[]
    for j in range(len(signature)):
        d.append(np.linalg.norm(signature[j] -proj_test_face[i]))
    dist.append(d)
    index_min.append(min_index(d))
    #y.append(ecludian_distance(signature[i],proj_test_face))
dist=np.array(dist)

In [64]:
signature.shape, proj_test_face.shape

((240, 50), (160, 50))

In [65]:
dist.shape

(160, 240)

In [66]:
min(dist[2]),dist[2,18]

(18136069.4679162, 27152783.724962823)

In [67]:
np.array(index_min)

array([ 48,  70,  46,   4, 230,  11,   7,   7,  12,  12, 119,  14,  18,
        19,  18,  18,  28,  28,  28,  28,  35,  35,  35,  35,  40,  40,
        39,  40,   0,  43,  71,  42,  53,  53,  53,  53,  59,  59,  56,
       134,  60,  63,  64,  16,  70,  66,  68,  69,  73,  76,  91,  91,
        81,  81,  79,  83,  85,  86,  84,  84,  90,  95,  91, 186,  98,
        97, 101,  98, 104, 104, 136, 107, 111, 110, 111, 113,  15,  12,
       119, 119, 122, 124, 180, 121, 126, 130, 129, 128, 202, 137, 137,
       201, 138, 142, 141, 140, 147,  78, 144, 144, 155,  36, 154, 155,
       157, 160, 126, 160, 167, 166, 167, 167, 172, 107, 102, 170,   0,
       179, 178,  51, 180, 180, 184, 180, 187, 190, 187, 188, 194,  79,
        80, 194, 202, 201, 200, 199, 207, 208, 209, 215, 215, 210, 215,
       215, 219, 221, 221, 219, 226, 224, 224, 224, 230, 228, 232, 232,
       238, 239, 237, 237])

In [68]:
count=0
for i in range(len(index_min)):
    if(Class_X[index_min[i]] ==Class_Y[i]):
        count+=1
count

132

In [69]:
print("Accuracy = ",count/len(index_min))

Accuracy =  0.825
